[package]
name = "database"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sea-orm = { version = "0.12.4", features = [
    "sqlx-mysql",
    "runtime-tokio-rustls",
    "macros",
] }
